#pragma once
#include "stdafx.h"

#ifndef ENTITYNAME_HPP
#define ENTITYNAME_HPP
std::map<std::string, std::string> EntityName {
    //player
    {"BP_PlayerPawn_SI_C" , "Player"},

    //shit
    {"Useless" , "Useless"},
    {"WorldSettings" , "Useless"},
    {"InstancedFoliageActor" , "Useless"},
    {"Water" , "Useless"},
    {"UnderWaterFog" , "Useless"},
    {"BP_STPlayerStart" , "Useless"},
    {"BP_STPlayerStart2" , "Useless"},
    {"BP_STPlayerStart3" , "Useless"},
    {"BP_STPlayerStart4" , "Useless"},
    {"BP_STPlayerStart5" , "Useless"},
    {"BP_MiniMapStandardPoint" , "Useless"},
    {"NavMeshBoundsVolume" , "Useless"},
    {"PostProcessMgr" , "Useless"},
    {"BP_BattleStart1_D1" , "Useless"},
    {"BP_BattleStart2_D1" , "Useless"},
    {"BP_BattleStart3_D1" , "Useless"},
    {"BP_BattleStart4_D1" , "Useless"},
    {"BP_BattleStart5_D1" , "Useless"},
    {"BP_BattleStart6_D1" , "Useless"},
    {"SociallandWaterSwimObject" , "Useless"},
    {"AIWorldVolume" , "Useless"},
    {"Socialland_ObjectPoolMgr" , "Useless"},
    {"BP_LevelGenerator2" , "Useless"},
    {"BP_LevelStreamVolumeContainer2" , "Useless"},
    {"BP_LevelStreamVolumeContainer" , "Useless"},
    {"SocialIsland_Main_C" , "Useless"},
    {"LevelStreamingVolume2" , "Useless"},
    {"Sub01_CarPark2" , "Useless"},
    {"Sub01_ChearPark2" , "Useless"},
    {"Sub01_DevArea6" , "Useless"},
    {"Sub01_DevArea7" , "Useless"},
    {"Sub01_DevArea8" , "Useless"},
    {"Sub01_DevArea9" , "Useless"},
    {"Sub01_DevArea10" , "Useless"},
    {"Sub01_DuleArea2" , "Useless"},
    {"Sub01_LakeIsland2" , "Useless"},
    {"Sub01_ShootArea2" , "Useless"},
    {"LevelStreamingVolume1" , "Useless"},
    {"Sub01_CarPark" , "Useless"},
    {"Sub01_ChearPark" , "Useless"},
    {"Sub01_DevArea2" , "Useless"},
    {"Sub01_DevArea5" , "Useless"},
    {"Sub01_DevArea4" , "Useless"},
    {"Sub01_DevArea1" , "Useless"},
    {"Sub01_DuleArea" , "Useless"},
    {"Sub01_DevArea3" , "Useless"},
    {"Sub01_LakeIsland" , "Useless"},
    {"Sub01_ShootArea" , "Useless"},
    {"BP_GlobalConfig" , "Useless"},
    {"DefaultPhysicsVolume" , "Useless"},
    {"ParticleEventManager" , "Useless"},
    {"CameraActor" , "Useless"},
    {"BP_PlayerController_SI_C" , "Useless"},
    {"BP_PlayerCameraManager_C" , "Useless"},
    {"CameraActor" , "Useless"},
    {"BP_HUD_SocialIsland_C" , "Useless"},
    {"SmartBearerManager" , "Useless"},
    {"BP_PaintDecalDetectLine1_GEN_VAR" , "Useless"},
    {"BP_PlayerState_SocialIsland_C" , "Useless"},
    {"BP_GameState_SocialIsland_C" , "Useless"},
    {"BP_MegaDrop_C" , "Useless"},
    {"Skill_Punch_Fist_bp_C" , "Useless"},
    {"Skill_Melee_Machete_BP_C" , "Useless"},
    {"Skill_Melee_Cowbar_BP_C" , "Useless"},
    {"Skill_Melee_Pan_BP_C" , "Useless"},
    {"Skill_Melee_Sickle_BP_C" , "Useless"},
    {"Skill_AdrenalineSyringe_BP_C" , "Useless"},
    {"Skill_Bandage_BP_C" , "Useless"},
    {"Skill_EnergyDrink_BP_C" , "Useless"},
    {"Skill_FirstAidKit_BP_C" , "Useless"},
    {"Skill_GasCan_BP_C" , "Useless"},
    {"Skill_MedKit_BP_C" , "Useless"},
    {"Skill_Painkiller_BP_C" , "Useless"},
    {"Skill_RapidAidbox_BP_C" , "Useless"},
    {"Skill_Grenade_Frag_BP_C" , "Useless"},
    {"Skill_Grenade_Molotov_BP_C" , "Useless"},
    {"Skill_Grenade_PoisonApple_BP_C" , "Useless"},
    {"Skill_Grenade_Smoke_BP_C" , "Useless"},
    {"Skill_Grenade_Stun_BP_C" , "Useless"},
    {"Skill_Grenade_Molotov_BP_C" , "Useless"},
    {"Skill_Grenade_Smoke_BP_2_C" , "Useless"},
    {"Skill_ProjSpikeTrap_BP_C" , "Useless"},
    {"Skill_Boss_StartFall_BP_C" , "Useless"},
    {"Skill_Boss_StartFall_Delay_BP_C" , "Useless"},
    {"Skill_IceDrink_BP_C" , "Useless"},
    {"Zombie10_GoToEarth_C" , "Useless"},
    {"Zombie10_Skill1_C" , "Useless"},
    {"Zombie10_Skill2_C" , "Useless"},
    {"Zombie10_Skill3_C" , "Useless"},
    {"Zombie11_CeilingLand_C" , "Useless"},
    {"Zombie11_Skill1_C" , "Useless"},
    {"Zombie11_Skill2_C" , "Useless"},
    {"Zombie11_Skill3_frozen_C" , "Useless"},
    {"Zombie1_GoToEarth_C" , "Useless"},
    {"Zombie10_GoToEarth_C" , "Useless"},
    {"Zombie1_Skill1_C" , "Useless"},
    {"Zombie10_GoToEarth_C" , "Useless"},
    {"Zombie1_Skill2_C" , "Useless"},
    {"Zombie1_Skill3_C" , "Useless"},
    {"Zombie1_Skill4_C" , "Useless"},
    {"Zombie2_Skill1_C" , "Useless"},
    {"Zombie3_GoToEarth_C" , "Useless"},
    {"Zombie4_Skill1_C" , "Useless"},
    {"Zombie4_Skill5_C" , "Useless"},
    {"Zombie4_Skill6_C" , "Useless"},
    {"Zombie5_Skill1_C" , "Useless"},
    {"Zombie6_GoToEarth_C" , "Useless"},
    {"Zombie6_Skill1_C" , "Useless"},
    {"Zombie6_Skill1_killself_C" , "Useless"},
    {"Zombie6_Skill1_L_C" , "Useless"},
    {"Zombie7_Skill1_C" , "Useless"},
    {"Zombie7_Skill2_C" , "Useless"},
    {"Zombie8_Skill1_C" , "Useless"},
    {"Zombie8_Skill2_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Skill_HitGround_BP_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Zombie8_Skill3_C" , "Useless"},
    {"Skill_JumpAndAttack_BP_C" , "Useless"},
    {"Skill_MegaThunder_BP_C" , "Useless"},
    {"Skill_RunAndAttack_BP_C" , "Useless"},
    {"Skill_ShieldHit_BP_C" , "Useless"},
    {"Skill_ShieldHit_L_BP_C" , "Useless"},
    {"Skill_ShieldHitGround_BP_C" , "Useless"},
    {"Skill_ShieldHitGround_L_BP_C" , "Useless"},
    {"Skill_SummonMonster_BP_C" , "Useless"},
    {"Skill_ThrowLandmine_BP_C" , "Useless"},
    {"Skill_ThrowPoisonBall_BP_1_C" , "Useless"},
    {"Skill_ThrowPoisonBall_BP_C" , "Useless"},
    {"Skill_ThrowPoisonBall_HighArc_BP" , "Useless"},
    {"Skill_ThrowPoisonBall_Ray_BP_C" , "Useless"},
    {"Skill_ThrowPoisonBall_RaySlow_BP" , "Useless"},
    {"Skill_VomitToixContinued_BP_C" , "Useless"},
    {"Skill_Zombie_Explosion_1_C" , "Useless"},
    {"Skill_Zombie_Explosion_C" , "Useless"},
    {"Skill_Zombie_Explosion_L_C" , "Useless"},
    {"Skill1_Tyrant_Hit_BP_C" , "Useless"},
    {"Skill_Boss_Landed_BP_C" , "Useless"},
    {"Skill_Boss_StartFall_BP_C" , "Useless"},
    {"Skill_Boss_StartFall_Delay_BP_C" , "Useless"},
    {"Skill_JumpMechanism_BP_C" , "Useless"},
    {"Skill_JumpMechanismByAssignPos_B" , "Useless"},
    {"Skill_StickHitGround_BP_C" , "Useless"},
    {"Skill_ThrowOilTank_BP_C" , "Useless"},
    {"Skill_TyranSummonMonster_BP_C" , "Useless"},
    {"Skill_Tyrant_HitAndMove_BP_C" , "Useless"},
    {"Skill_Tyrant_ThrowRock_BP_C" , "Useless"},
    {"ZombieDrG_JumpAndAttack_C" , "Useless"},
    {"ZombieDrG_Skill1_C" , "Useless"},
    {"Skill_ClientShowUI_BP_C" , "Useless"},
    {"Skill_TrainCoin_BP_C" , "Useless"},
    {"Skill_RoastChicken_BP_C" , "Useless"},
    {"Skill_DuckHunt_BP_C" , "Useless"},
    {"Skill_ParachuteLand_BP_C" , "Useless"},
    {"Skill_DuelFail_BP_C" , "Useless"},
    {"Skill_PickupIce_BP_C" , "Useless"},
    {"Skill_WingUp_BP_C" , "Useless"},
    {"Skill_GiveBackpackItem_BP_C" , "Useless"},
    {"Skill_Swing_C" , "Useless"},
    {"Skill_GiveHeart_BP_C" , "Useless"},
    {"Skill_Make_Wish_BP_C" , "Useless"},
    {"Skill_GoldCrowInteraction_BP_C" , "Useless"},
    {"Skill_Grenade_Sticky_Bomb_C" , "Useless"},
    {"SliceMusicalNote_C" , "Useless"},
    {"StartMusicGame_C" , "Useless"},
    {"Skill_FinishInteractAtOnce_BP_C" , "Useless"},
    {"BP_FerrisWheelCar_C" , "Useless"},
    {"ShareWidgetRTManager" , "Useless"},
    {"BP_PlayerRifleBullet_C" , "Useless"},
    {"BP_PlayerRifleBulletImpact_C" , "Useless"},
    {"BP_PlayerShotgunBullet_C" , "Useless"},
    {"BP_PlayerSniperBullet_C" , "Useless"},
    {"BP_PaintDecalDetectLine1_GEN_VAR" , "Useless"},
    {"EWeatherStatusType" , "Useless"},
    {"StructProperty" , "Useless"},
    {"None" , "Useless"},
    {"InterfaceProperty" , "Useless"},
    {"OtherPetVisibleSettingChanged" , "Useless"},
    {"FPPCameraComp" , "Useless"},
    {"BP_DecalBakingActor_C" , "Useless"},
    {"BoolProperty" , "Useless"},
    {"DelegateProperty" , "Useless"},
    {"Landsca3138peGizmoActiveActor" , "Useless"},
    {"BP_ObjectPoolManager_AllMode_C" , "Useless"},
    {"Zombie11_GoToEarth_C" , "Useless"},
    {"Zombie4_Skill2_C" , "Useless"},
    {"Zombie4_Skill3_C" , "Useless"},
    {"Skill_ThrowPoisonBall_HighArc_BP_C" , "Useless"},
    {"Skill_ThrowPoisonBall_RaySlow_BP_C" , "Useless"},
    {"Skill_JumpMechanismByAssignPos_BP_C" , "Useless"},
    {"VehicleDataMgr" , "Useless"},
    {"BP_Rifle_M416_C" , "Useless"},
    {"ObjectProperty" , "Useless"},
    {"Cylinder" , "Useless"},
    {"ClientFeedbackZombieMeleeDamage" , "Useless"},
    {"DeliverNeedGetCloser" , "Useless"},
    {"3138" , "Useless"},
    {"LandscapeGizmoActiveActor" , "Useless"},
    {"Timer" , "Useless"},
    {"newVersion" , "Useless"},
    {"AnimationCurves" , "Useless"},
    {"BP_PaintDecalDetectLine1_GEN_VARIABLE_BP_PaintDecalDetectLine1_C" , "Useless"},
    {"BP_Grenade_Apple_Weapon_Wrapper_C" , "Useless"},
    {"BP_Sniper_AWM_C" , "Useless"},
    {"BP_Sniper_Mosin_C" , "Useless"},
    {"BP_Pistol_R1895_C" , "Useless"},
    {"BP_Rifle_AKM_C" , "Useless"},
    {"BP_Sniper_AWM_C" , "Useless"},
    {"BP_Rifle_M762_C" , "Useless"},
    {"BP_Sniper_SKS_C" , "Useless"},
    {"BP_Rifle_AUG_C" , "Useless" },
    {"BP_Rifle_M16A4_C" , "Useless" },
    {"BP_Sniper_Kar98k_C" , "Useless"},
    {"ByteProperty" , "Useless"},
    {"IntProperty" , "Useless"},
    {"Transient" , "Useless"},
    {"StrProperty" , "Useless"},
    {"BoxSphereBounds" , "Useless"},
    {"ScriptStruct" , "Useless"},
    {"RenderCore" , "Useless"},
    {"UGameModeService_Original" , "Useless"},
    {"DoubleProperty" , "Useless"},
    {"Int16Property" , "Useless"},
    {"MaterialAssest" , "Useless"},
    {"BombDuckDieParticle_C" , "Useless"},
    {"DuckDieParticle_C" , "Useless"},
    {"IdeaDecalActor" , "Useless"},
    {"IdeaDecalManager" , "Useless"},
    {"ParticleCacheMgr" , "Useless"},
    {"UAnimCompress_PerTrackCompression" , "Useless"},
    {"UAsyncActionLoadPrimaryAssetBase" , "Useless"},
    {"ReceiveBeginPlay" , "Useless"},
    {"EPrimaryAssetCookRule" , "Useless"},
    {"UnnamedCategry" , "Useless"},
    {"FPrimitiveUniformShaderParameters" , "Useless"},
    {"EAnimCurveType" , "Useless"},
    {"MarkerSyncData" , "Useless"},
    {"UAnimStateMachineTypes" , "Useless"},
    {"TCopyDataCS<1>" , "Useless"},
    {"FStaticMeshStaticLightingMesh_IntersectLightRay<1>" , "Useless"},
    {"EBoneAxis" , "Useless"},
    {"UModAdapter" , "Useless"},
    {"FSimpleElementMaskedGammaPS_SRGB" , "Useless"},
    {"AnimationKeyFormat" , "Useless"},
    {"EMontageNotifyTickType" , "Useless"},
    {"FScreenMaskPS<false>" , "Useless"},
    {"EBoneRotationSource" , "Useless"},
    {"FSimpleElementMaskedGammaPS_SRGBEncodedSE_BLEND_Masked" , "Useless"},
    {"PrimaryAssetRules" , "Useless"},
    {"UAERecastNavMesh-Mannequin" , "Useless"},
    {"IsNoAuthMode" , "Useless"},
    {"StartBoosting0" , "Useless"},
    {"GameMsgCache" , "Useless"},
    {"SetSelfieCameraDefRotation" , "Useless"},
    {"BP_radiation" , "Useless"},
    {"ReflectionAdjustmentVolume4" , "Useless"},
    {"BP_SoftBoundary" , "Useless"},
    {"BP_STPlayerStart43" , "Useless"},
    {"BP_STPlayerStart42" , "Useless"},
    {"BP_STPlayerStart41" , "Useless"},
    {"BP_STPlayerStart44" , "Useless"},
    {"BP_STPlayerStart60" , "Useless"},
    {"BP_STPlayerStart59" , "Useless"},
    {"BP_STPlayerStart58" , "Useless"},
    {"BP_STPlayerStart57" , "Useless"},
    {"BP_STPlayerStart25" , "Useless"},
    {"BP_STPlayerStart29" , "Useless"},
    {"BP_STPlayerStart28" , "Useless"},
    {"BP_STPlayerStart26" , "Useless"},
    {"PetGyrfalconCharacter_C" , "Useless"},
    {"BuildingKanerjing_Trigger" , "Useless"},
    {"PhysicsVolume_Water" , "Useless"},
    {"Actor" , "Useless"},
    {"B" , "Useless"},
    {"TreasureBox_InteractiveActor_C" , "Useless"},
    {"UBTTaskGener" , "Useless"},
  

    {"AirAttackBomb_C", "Air Bomb"},


    //vehicle
    {"BP_VH_Buggy_2_C" , "Buggy"},
    {"BP_VH_Buggy_C" , "Buggy"},
    {"BP_VH_Buggy_3_C" , "Buggy"},
    {"VH_Motorcycle_1_C" , "Motorcycle"},
    {"VH_Dacia_C" , "Dacia"},
    {"VH_PG117_C" , "PG117"},
    {"VH_UAZ01_C" , "UAZ"},
    {"AquaRail_1_C" , "Aqua Rail"},
    {"Mirado_open_4_C" , "Mirado"},
    {"water_Plane" , "Water Plane"},
    {"VH_UAZ02_C" , "UAZ"},
    {"VH_UAZ03_C" , "UAZ"},
    {"VH_Motorcycle_C" , "Motorcycle"},
    {"VH_Dacia_2_C" , "Dacia"},
    {"VH_CoupeRB_1_C" , "Coupe RB"},
    {"VH_Scooter_C" , "Scooter"},
    {"VH_MotorcycleCart_C" , "Motorcycle Cart"},
    {"VH_Dacia_4_C" , "Dacia"},
    {"VH_Motorglider_C" , "Motorglider"},
    {"Rony_3_C" , "Rony"},
    {"VH_Scooter_4_C" , "Rony"},
    {"BP_VH_Bigfoot_C" , "Bigfoot"},

    //melee
    {"BP_WEP_Sickle_Pickup_C" , "Sickle"},
    {"BP_WEP_Pan_Pickup_C" , "Pan"},
    {"BP_WEP_Machete_Pickup_C" , "Machete"},
    {"BP_WEP_Cowbar_Pickup_C" , "Cowbar"},

    //awm 2.0
    {"BP_Other_CrossBow_Wrapper_C" , "CrossBow"},
    {"BP_Ammo_Bolt_Pickup_C" , "Bolt"},
    {"BP_ZDD_Crossbow_Q_Pickup_C" , "Quiver"},

    //sr
    {"BP_Sniper_AWM_Wrapper_C" , "AWM"},
    {"BP_Sniper_M24_Wrapper_C" , "M24"},
    {"BP_Sniper_Kar98k_Wrapper_C" , "Kar98k"},
    {"BP_Sniper_Win94_Wrapper_C" , "Win94"},
    {"BP_Sniper_Mosin_Wrapper_C" , "Mosin Nagant"},

    //dmr
    {"BP_Sniper_QBU_Wrapper_C" , "QBU"},
    {"BP_Sniper_SLR_Wrapper_C" , "SLR"},
    {"BP_Sniper_SKS_Wrapper_C" , "SKS"},
    {"BP_WEP_Mk14_Pickup_C" , "Mk14"},
    {"BP_Sniper_Mini14_Wrapper_C" , "Mini14"},
    {"BP_Sniper_VSS_Wrapper_C" , "VSS"},
    {"BP_Sniper_MK12_Wrapper_C" , "MK12"},

    //ar
    {"BP_Rifle_AUG_Wrapper_C" , "AUG"},
    {"BP_Rifle_M762_Wrapper_C" , "M762"},
    {"BP_Rifle_SCAR_Wrapper_C" , "SCAR"},
    {"BP_Rifle_QBZ_Wrapper_C" , "QBZ"},
    {"BP_Rifle_M416_Wrapper_C" , "M416"},
    {"BP_Rifle_M16A4_Wrapper_C" , "M16A4"},
    {"BP_Rifle_Mk47_Wrapper_C" , "Mk47"},
    {"BP_Rifle_G36_Wrapper_C" , "G36"},
    {"BP_Other_DP28_Wrapper_C" , "DP28"},
    {"BP_Other_M249_Wrapper_C" , "M249"},
    {"BP_Rifle_AKM_Wrapper_C" , "AKM"},
    {"BP_Rifle_Groza_Wrapper_C" , "Groza"},
    {"BP_Rifle_FAMAS_Wrapper_C" , "FAMAS"},

    //shotgun
    {"BP_ShotGun_DP12_Wrapper_C" , "DP12"},
    {"BP_ShotGun_S12K_Wrapper_C" , "S12K"},
    {"BP_ShotGun_S686_Wrapper_C" , "S686"},
    {"BP_ShotGun_S1897_Wrapper_C" , "S1897"},
    {"BP_ShotGun_SawedOff_Wrapper_C" , "Sawed Off"},
    {"BP_ShotGun_M1014_Wrapper_C" , "M1014"},

    //smg
    {"BP_MachineGun_PP19_Wrapper_C" , "PP19"},
    {"BP_MachineGun_TommyGun_Wrapper_C" , "Tommy Gun"},
    {"BP_MachineGun_MP5K_Wrapper_C" , "MP5K"},
    {"BP_MachineGun_UMP9_Wrapper_C" , "UMP9"},
    {"BP_MachineGun_Vector_Wrapper_C" , "Vector"},
    {"BP_MachineGun_Uzi_Wrapper_C" , "Uzi"},
    {"BP_MachineGun_P90_Wrapper_C" , "P90"},

    //pistol
    {"BP_Pistol_R1895_Wrapper_C" , "R1895"},
    {"BP_Pistol_Vz61_Wrapper_C" , "Vz61"},
    {"BP_Pistol_P92_Wrapper_C" , "P92"},
    {"BP_Pistol_P18C_Wrapper_C" , "P18C"},
    {"BP_Pistol_R45_Wrapper_C" , "R45"},
    {"BP_Pistol_P1911_Wrapper_C" , "P1911"},

    //de 1 tap
    {"BP_Pistol_DesertEagle_Wrapper_C" , "Desert Eagle"},

    //ammo
    {"BP_Ammo_762mm_Pickup_C" , "7.62mm"},
    {"BP_Ammo_45ACP_Pickup_C" , ".45ACP"},
    {"BP_Ammo_556mm_Pickup_C" , "5.56mm"},
    {"BP_Ammo_9mm_Pickup_C" , "9mm"},
    {"BP_Ammo_300Magnum_Pickup_C" , "300Magnum"},
    {"BP_Ammo_12Guage_Pickup_C" , "12Guage"},


    //air drop
    {"BP_Pistol_Flaregun_Wrapper_C" , "Flaregun"},
    { "BP_Ammo_Flare_Pickup_C" , "Flare" },

    //scope
    {"BP_MZJ_8X_Pickup_C" , "x8"},
    {"BP_MZJ_6X_Pickup_C" , "x6"},
    {"BP_MZJ_4X_Pickup_C" , "x4"},
    {"BP_MZJ_3X_Pickup_C" , "x3"},
    {"BP_MZJ_2X_Pickup_C" , "x2"},
    {"BP_MZJ_QX_Pickup_C" , "Holo"},
    {"BP_MZJ_HD_Pickup_C" , "Reddot"},
    {"BP_MZJ_SideRMR_Pickup_C" , "Canted Sight"},
    {"BP_MZJ_2X_Pickup_C_Recucled" , "x2"},

    //bag
    {"PickUp_BP_Bag_Lv3_C" , "Bag 3"},
    {"PickUp_BP_Bag_Lv3_B_C" , "Bag 3"},
    {"PickUp_BP_Bag_Lv2_C" , "Bag 2"},
    {"PickUp_BP_Bag_Lv2_B_C" , "Bag 2"},
    {"PickUp_BP_Bag_Lv1_C" , "Bag 1"},
    {"PickUp_BP_Bag_Lv1_B_C" , "Bag 1"},

    //armor
    {"PickUp_BP_Armor_Lv3_C" , "Armor 3"},
    {"PickUp_BP_Armor_Lv2_C" , "Armor 2"},
    {"PickUp_BP_Armor_Lv1_C" , "Armor 1"},

    //helmet
    {"PickUp_BP_Helmet_Lv3_C" , "Helmet 3"},
    {"PickUp_BP_Helmet_Lv2_C" , "Helmet 2"},
    {"PickUp_BP_Helmet_Lv2_B_C" , "Helmet 2"},
    {"PickUp_BP_Helmet_Lv1_C" , "Helmet 1"},
    {"PickUp_BP_Helmet_Lv1_B_C" , "Helmet 1"},

    //sr mag
    {"BP_DJ_Sniper_E_Pickup_C" , "SR-Mag Extended"},
    {"BP_DJ_Sniper_Q_Pickup_C" , "SR-Mag Quickdraw"},
    {"BP_DJ_Sniper_EQ_Pickup_C" , "SR-Mag Extended Quickdraw"},

    //ar mag
    {"BP_DJ_Large_E_Pickup_C" , "AR-Mag Extended"},
    {"BP_DJ_Large_EQ_Pickup_C" , "AR-Mag Extended Quickdraw"},
    {"BP_DJ_Large_Q_Pickup_C" , "AR-Mag QuickDraw"},

    //smg mag
    {"BP_DJ_Mid_E_Pickup_C" , "SMG-Mag Extended"},
    {"BP_DJ_Mid_EQ_Pickup_C" , "SMG-Mag Extended Quickdraw"},
    {"BP_DJ_Mid_Q_Pickup_C" , "SMG-Mag QuickDraw"},

    //compensator
    {"BP_QK_Sniper_Compensator_Pickup_C" , "SR Compensator"},
    {"BP_QK_Large_Compensator_Pickup_C" , "AR Compensator"},
    {"BP_QK_Mid_Compensator_Pickup_C" , "SMG Compensator"},

    //flashhider
    {"BP_QK_Sniper_FlashHider_Pickup_C" , "SR FlashHider"},
    {"BP_QK_Large_FlashHider_Pickup_C" , "AR FlashHider"},
    {"BP_QK_Mid_FlashHider_Pickup_C" , "SMG FlashHider"},

    //suppressor
    {"BP_QK_Sniper_Suppressor_Pickup_C" , "SR Suppressor"},
    {"BP_QK_Large_Suppressor_Pickup_C" , "AR ASuppressorR"},
    {"BP_QK_Mid_Suppressor_Pickup_C" , "SMG Suppressor"},

    {"BP_QK_Large_ExtendedBarrel_Pickup_C" , "Extended Barrel"},

    //stock
    {"BP_QT_A_Pickup_C" , "Tactical Stock"},
    {"BP_QT_Sniper_Pickup_C" , "Check Pad"},
    {"BP_QT_UZI_Pickup_C" , "UZI Stock"},

    //grip
    {"BP_WB_Angled_Pickup_C" , "Angled Foregrip"},
    {"BP_WB_HalfGrip_Pickup_C" , "Half Grip"},
    {"BP_WB_Vertical_Pickup_C" , "Vertical Foregrip"},
    {"BP_WB_Lasersight_Pickup_C" , "Lasersight"},
    {"BP_WB_LightGrip_Pickup_C" , "Light Grip"},
    {"BP_WB_ThumbGrip_Pickup_C" , "Thumb Grip"},

    //shotgun attachements
    { "BP_QK_DuckBill_Pickup_C" , "Duckbill" },
    { "BP_QK_Choke_Pickup_C" , "Choke" },

    //misc
    {"BP_ZDD_Sniper_Pickup_C" , "Bullet Loop" },
    {"GasCan_Destructible_Pickup_C" , "Gas Can" },
    {"BP_SpikeTrap_Wrapper_C" , "Spike Trap" },


    /*{"PickUpListWrapperActor" , "Player Crate" },*/
    {"PlayerDeadInventoryBox_C" , "Player Crate" },
    {"BP_AirDropBox_C" , "Air Drop" },

    //energy
    {"Firstaid_Pickup_C" , "Firstaid"},
    {"FirstAidbox_Pickup_C" , "Medkit"},
    {"Injection_Pickup_C" , "Adrenaline"},
    {"Pills_Pickup_C" , "Pain Killer"},
    {"Drink_Pickup_C" , "Energy Drink"},
    {"Bandage_Pickup_C" , "Bandage"},

    //boom
    {"BP_Grenade_Shoulei_Weapon_Wrapper_C" , "Bomb"},
    {"BP_Grenade_Smoke_Weapon_Wrapper_C" , "Nade Smoke"},
    {"BP_Grenade_Burn_Weapon_Wrapper_C" , "Molotov" },
    {"BP_Grenade_Stun_Weapon_Wrapper_C" , "Stun" }

};

std::map<std::string, sf::Color> EntityColor{
    //vehicle
    {"Buggy" , sf::Color::Green},
    {"Motorcycle" , sf::Color::Green},
    {"Dacia" , sf::Color::Green},
    {"PG117" , sf::Color::Green},
    {"UAZ" , sf::Color::Green},
    {"Aqua Rail" , sf::Color::Green},
    {"Mirado" , sf::Color::Green},
    {"Water Plane" , sf::Color::Green},
    {"Coupe RB" , sf::Color::Green},
    {"Motorcycle Cart" , sf::Color::Green},
    {"Motorglider" , sf::Color::Green},
    {"Scooter" , sf::Color::Green},
    {"Bigfoot" , sf::Color::Green},

    //air drop
    {"Flare", sf::Color::Red},
    {"Flaregun", sf::Color::Red},


    //melee
    {"Sickle" , sf::Color(128,128,128)},
    {"Pan" , sf::Color(128,128,128)},
    {"Machete" , sf::Color(128,128,128)},
    {"Cowbar" , sf::Color(128,128,128)},

    //awm 2.0
    {"CrossBow" , sf::Color(128,128,128)},
    {"Bolt" , sf::Color(128,128,128)},
    {"Quiver" , sf::Color(128,128,128)},

    //sr
    {"AWM" , sf::Color::Red},
    {"M24" , sf::Color(255,165,0)},
    {"Kar98k" , sf::Color(255,165,0)},
    {"Win94" , sf::Color(255,165,0)},
    {"Mosin Nagant" , sf::Color(255,165,0)},

    //dmr
    {"QBC" , sf::Color(255,165,0)},
    {"SLR" , sf::Color(255,165,0)},
    {"SKS" , sf::Color(255,165,0)},
    {"Mk14" , sf::Color::Red},
    {"Mini14" , sf::Color(255,165,0)},
    {"VSS" , sf::Color(255,165,0)},
    {"MK12" , sf::Color(255,165,0)},

    //ar
    {"AUG" , sf::Color::Red},
    {"M762" , sf::Color(255,165,0)},
    {"SCAR" , sf::Color(255,165,0)},
    {"QBZ" , sf::Color(255,165,0)},
    {"M416" , sf::Color(255,165,0)},
    {"M16A4" , sf::Color(255,165,0)},
    {"Mk47" , sf::Color(255,165,0)},
    {"G36" , sf::Color(255,165,0)},
    {"DP28" , sf::Color(255,165,0)},
    {"M249" , sf::Color::Red},
    {"AKM" , sf::Color(255,165,0)},
    {"Groza" , sf::Color::Red},
    {"FAMAS" , sf::Color(255,165,0)},

    //shotgun
    {"DP12" , sf::Color::Red},
    {"S12K" , sf::Color(135,206,250)},
    {"S686" , sf::Color(135,206,250)},
    {"S1897" , sf::Color(135,206,250)},
    {"Sawed Off" , sf::Color(135,206,250)},
    {"M1014" , sf::Color(135,206,250)},

    //smg
    {"PP19" , sf::Color(135,206,250)},
    {"Tommy Gun" , sf::Color(135,206,250)},
    {"MP5K" , sf::Color(135,206,250)},
    {"UMP9" , sf::Color(135,206,250)},
    {"Vector" , sf::Color(135,206,250)},
    {"Uzi" , sf::Color(135,206,250)},

    //pistol
    {"R1895" , sf::Color(128,128,128)},
    {"Vz61" , sf::Color(128,128,128)},
    {"P92" , sf::Color(128,128,128)},
    {"P18C" , sf::Color(128,128,128)},
    {"R45" , sf::Color(128,128,128)},
    {"P1911" , sf::Color(128,128,128)},

    //de 1 tap
    {"Desert Eagle" , sf::Color(128,128,128)},

    //ammo
    {"7.62mm" , sf::Color(255,165,0)},
    {".45ACP" , sf::Color(135,206,250)},
    {"5.56mm" , sf::Color(255,165,0)},
    {"9mm" , sf::Color(135,206,250)},
    {"300Magnum" , sf::Color::Red},
    {"12Guage" , sf::Color(135,206,250) },

    //scope
    {"x8" , sf::Color::Red },
    {"x6" , sf::Color::Red },
    {"x4" , sf::Color(135,206,250) },
    {"x3" , sf::Color(135,206,250) },
    {"x2" , sf::Color(135,206,250) },
    {"Holo" , sf::Color(128,128,128) },
    {"Reddot" , sf::Color(255,165,0)},
    {"Canted Sight" , sf::Color(255,165,0) },

    //bag
    {"Bag 3" , sf::Color(255,165,0) },
    {"Bag 2" , sf::Color(135,206,250)},
    {"Bag 1" , sf::Color(128,128,128) },

    //armor
    {"Armor 3" , sf::Color(255,165,0) },
    {"Armor 2" , sf::Color(135,206,250) },
    {"Armor 1" , sf::Color(128,128,128) },

    //helmet
    {"Helmet 3" , sf::Color(255,165,0) },
    {"Helmet 2" , sf::Color(135,206,250) },
    {"Helmet 1" , sf::Color(128,128,128) },

    //sr mag
    {"SR-Mag Extended" , sf::Color(135,206,250) },
    {"SR-Mag Quickdraw" , sf::Color(135,206,250) },
    {"SR-Mag Extended Quickdraw" , sf::Color(255,165,0) },

    //ar mag
    {"AR-Mag Extended" , sf::Color(135,206,250) },
    {"AR-Mag Extended Quickdraw" , sf::Color(255,165,0) },
    {"AR-Mag QuickDraw" ,sf::Color(135,206,250) },

    //smg mag
    {"SMG-Mag Extended" , sf::Color(135,206,250) },
    {"SMG-Mag Extended Quickdraw" , sf::Color(255,165,0) },
    {"SMG-Mag QuickDraw" , sf::Color(135,206,250) },

    //compensator
    {"SR Compensator" , sf::Color(135,206,250) },
    {"AR Compensator" , sf::Color(135,206,250) },
    {"SMG Compensator" , sf::Color(135,206,250) },

    //flashhider
    {"SR FlashHider" , sf::Color(135,206,250) },
    {"AR FlashHider" , sf::Color(135,206,250) },
    {"SMG FlashHider" , sf::Color(135,206,250) },

    //suppressor
    {"SR Suppressor" , sf::Color(135,206,250) },
    {"AR Suppressor" , sf::Color(135,206,250) },
    {"SMG Suppressor" , sf::Color(135,206,250) },

    {"Extended Barrel" , sf::Color(135,206,250) },

    //stock
    {"Tactical Stock" , sf::Color(135,206,250) },
    {"Check Pad" , sf::Color(135,206,250) },
    {"UZI Stock" , sf::Color(135,206,250) },

    //grip
    {"Angled Foregrip" , sf::Color(135,206,250) },
    {"Half Grip" , sf::Color(135,206,250) },
    {"Vertical Foregrip" ,sf::Color(135,206,250) },
    {"Lasersight" , sf::Color(135,206,250) },
    {"Light Grip" , sf::Color(135,206,250) },
    {"Thumb Grip" ,sf::Color(135,206,250) },

    //shotgun attachements
    { "Duckbill" , sf::Color(135,206,250) },
    { "Choke" , sf::Color(135,206,250) },

    //misc
    {"Bullet Loop" , sf::Color(135,206,250) },
    {"Gas Can" , sf::Color(135,206,250) },
    {"Spike Trap" , sf::Color(135,206,250) },

    {"Player Crate" , sf::Color(0,206,250) },
    {"Air Drop" , sf::Color(0,206,250) },
    {"Air Bomb" , sf::Color::Red },

    //energy
    {"Firstaid" , sf::Color(255,182,193)},
    {"Medkit" , sf::Color(255,182,193) },
    {"Adrenaline" , sf::Color(255,182,193) },
    {"Pain Killer" , sf::Color(255,182,193) },
    {"Energy Drink" , sf::Color(255,182,193) },
    {"Bandage" , sf::Color(255,182,193) },

    //boom
    {"Bomb" , sf::Color::Red },
    {"Smoke" , sf::Color::White},
    { "Molotov" , sf::Color::Red },
    { "Stun" , sf::Color(135, 206, 250) }
};
#endif